import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { main, HELP } from '../../bin/wtk.js';
import { buildPlan, gitProof, loadManifest, resolveModules } from '../../scripts/installer/engine.js';
import { knowledgeTransfers } from '../../scripts/installer/knowledge.js';
import { renderPlan, runInstallWizard } from '../../scripts/installer/terminal.js';
import { applyTransaction, hasInterruptedTransaction, prepareBackup, restoreInterrupted } from '../../scripts/installer/transaction.js';
import { stageAgentPackets } from '../../scripts/installer/packets.js';
const sourceRoot = path.resolve(import.meta.dirname, '../..');
const temp = () => fs.mkdtempSync(path.join(os.tmpdir(), 'installer-ac-'));
const io = (answers, output = []) => { let index = 0; return { input: async () => answers[index++], write: (value) => output.push(value) }; };
function snapshot(root) {
  const result = {};
  const walk = (dir) => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const relative = path.relative(root, path.join(dir, entry.name)).split(path.sep).join('/');
      if (entry.isDirectory() && !entry.isSymbolicLink()) walk(path.join(dir, entry.name));
      else if (entry.isFile()) result[relative] = { bytes: fs.readFileSync(path.join(dir, entry.name)).toString('base64'), mode: fs.statSync(path.join(dir, entry.name)).mode & 0o7777 };
      else result[relative] = `type:${entry.isSymbolicLink() ? 'symlink' : entry.name}`;
    }
  };
  walk(root); return result;
}
function copyStaged(root, result) { for (const [relative, content] of Object.entries(result.staged)) { const file = path.join(root, relative); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, content); } for (const [relative, target] of Object.entries(result.links || {})) { const file = path.join(root, relative); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.symlinkSync(target, file); } }
function gitFixture(root) { execFileSync('git', ['init', '-q'], { cwd: root }); execFileSync('git', ['config', 'user.email', 'installer@test.invalid'], { cwd: root }); execFileSync('git', ['config', 'user.name', 'Installer Test'], { cwd: root }); fs.writeFileSync(path.join(root, '.gitignore'), 'node_modules/\n'); execFileSync('git', ['add', '.gitignore'], { cwd: root }); execFileSync('git', ['commit', '-qm', 'fixture'], { cwd: root }); }
function seed(root, modules = ['core']) { const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: modules }); copyStaged(root, result); return result; }
function plan(root, modules = ['core']) { return buildPlan({ sourceRoot, targetRoot: root, selectedModules: modules }).plan; }
const digest = (value) => crypto.createHash('sha256').update(value).digest('hex');
function normalizedOutcome(result, targetRoot) { const plan = { selected: result.plan.selectedModules, status: result.plan.status, actions: result.plan.actions.map((action) => ({ path: action.path, kind: action.kind, modules: action.modules, reason: action.reason ?? null, sourceSha256: action.sourceSha256 ?? null, installedSha256: action.installedSha256 ?? null })), unresolved: result.plan.unresolved, retired: result.plan.retired }; const packets = Object.fromEntries(Object.entries(stageAgentPackets(sourceRoot, targetRoot)).sort().map(([relative, content]) => [relative, digest(content)])); const tree = Object.fromEntries(Object.entries(result.staged).sort().map(([relative, content]) => [relative, { sha256: digest(content), mode: 0o644 }])); return { plan: digest(JSON.stringify(plan)), manifest: digest(JSON.stringify(result.manifest)), packets: digest(JSON.stringify(packets)), tree: digest(JSON.stringify(tree)), actionCount: result.plan.actions.length, manifestCount: Object.keys(result.manifest.files).length }; }

test('AC CLI-001 canonical install binds cwd and opens module selection', async () => { const root = temp(); const stdout = { isTTY: true, output: '', write(value) { this.output += value; } }; const answers = ['1', 'n']; const result = await main(['install'], { stdin: { isTTY: true }, stdout, stderr: { write() {} }, targetRoot: root, sourceRoot, requireGit: false, readline: { question: async () => answers.shift(), close() {} } }); assert.equal(result, 0); assert.match(stdout.output, new RegExp(`Target: ${root}`)); assert.match(stdout.output, /Modules \[1-3, comma-separated\]:/); });
test('AC CLI-002 rejects non-TTY with exact guidance and zero residue', async () => { const stdout = { isTTY: false, write() {} }; const stderr = { isTTY: false, text: '', write(value) { this.text += value; } }; const root = temp(); const result = await main(['install'], { stdin: stdout, stdout, stderr, targetRoot: root }); assert.equal(result, 2); assert.equal(stderr.text, 'Interactive terminal required; run this command in a TTY.\n'); assert.deepEqual(fs.readdirSync(root), []); });
test('AC CLI-003 help documents install, modules, cwd, backups, and Node 18', async () => { const stdout = { output: '', write(value) { this.output += value; } }; assert.equal(await main(['--help'], { stdin: { isTTY: false }, stdout, stderr: { write() {} } }), 0); for (const value of ['install', 'core', 'quality', 'extras', 'current working directory', 'Backups', 'Node.js 18']) assert.match(stdout.output, new RegExp(value)); });
test('AC PORT-001 Node-only planner stages the canonical catalog without Python', () => { const root = temp(); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); assert.equal(result.plan.packageVersion, JSON.parse(fs.readFileSync(path.join(sourceRoot, 'package.json'), 'utf8')).version); assert.ok(result.staged['.my-workflow/adoption.json']); assert.ok(result.staged['.agents/skills/wtk/SKILL.md']); assert.equal(Object.keys(result.staged).some((relative) => relative.includes('adopt.py')), false); });
test('AC PORT-002 Git process proof has literal argv and shell disabled', () => { const root = temp(); const calls = []; const runner = (command, args, options) => { calls.push({ command, args, options }); return args[1] === '--is-inside-work-tree' ? 'true' : args[1] === '--show-toplevel' ? root : args[1] === '--verify' ? 'HEAD' : ''; }; assert.equal(gitProof(root, runner), true); assert.equal(calls.every((call) => call.command === 'git' && call.options.cwd === root && call.options.shell === false), true); });
test('IT-009 core adoption packages intelligence routing and reports pinned setup without changing app dependencies', async () => { const target = temp(); const packageJson = '{"name":"consumer","dependencies":{"app":"1.0.0"}}\n'; fs.writeFileSync(path.join(target, 'package.json'), packageJson); const output = []; const result = await runInstallWizard({ sourceRoot, targetRoot: target, ...io(['1', 'y', 'y'], output) }); assert.equal(result.code, 0); assert.ok(result.result); assert.ok(result.plan); assert.equal(fs.readFileSync(path.join(target, 'package.json'), 'utf8'), packageJson); const text = output.join('\n'); assert.match(text, /npm install --save-dev --save-exact @nanonets\/graft@0\.10\.1/); assert.match(text, /uv tool install graphifyy==0\.9\.14/); assert.match(text, /manual; not executed/); });
test('IT-009 core adoption stages intelligence CLI and routing reference', () => { const result = buildPlan({ sourceRoot, targetRoot: temp(), selectedModules: ['core'] }); assert.ok(result.staged['.agents/skills/wtk-config/scripts/repository_intelligence.py']); assert.ok(result.staged['.agents/skills/wtk-lean/references/build.md']); assert.ok(result.staged['docs/toolkit/repository-intelligence.md']); });
test('SEP-01/SEP-02 core docs use toolkit namespace and preserve generic consumer directories', () => { const root = temp(); const guideline = path.join(root, 'docs/guidelines/local.md'); const workflow = path.join(root, 'docs/workflow/local.md'); fs.mkdirSync(path.dirname(guideline), { recursive: true }); fs.mkdirSync(path.dirname(workflow), { recursive: true }); fs.writeFileSync(guideline, 'consumer guideline\n'); fs.writeFileSync(workflow, 'consumer workflow\n'); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); const paths = Object.keys(result.staged); assert.ok(paths.includes('docs/toolkit/README.md')); assert.ok(paths.includes('docs/toolkit/guidelines/CONTEXT-BUDGET.md')); assert.equal(paths.some((relative) => relative.startsWith('docs/guidelines/')), false); assert.equal(paths.some((relative) => relative.startsWith('docs/workflow/')), false); assert.equal(result.plan.actions.some((action) => action.path.startsWith('docs/guidelines/') || action.path.startsWith('docs/workflow/')), false); assert.equal(fs.readFileSync(guideline, 'utf8'), 'consumer guideline\n'); assert.equal(fs.readFileSync(workflow, 'utf8'), 'consumer workflow\n'); });
test('IT-011 and SEC-002 generated intelligence state stays out of Git and staged adoption', () => { const root = temp(); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); const gitignore = result.staged['.gitignore'].toString().split(/\r?\n/); for (const entry of ['graft/', 'graphify-out/', '.repository-intelligence/']) assert.ok(gitignore.includes(entry), entry); const searchignore = result.staged['.ignore'].toString().split(/\r?\n/); for (const entry of ['graphify-out/', '.repository-intelligence/']) assert.ok(searchignore.includes(entry), entry); assert.equal(Object.keys(result.staged).some((relative) => relative.startsWith('graft/') || relative.startsWith('graphify-out/') || relative.startsWith('.repository-intelligence/')), false); fs.writeFileSync(path.join(root, '.gitignore'), result.staged['.gitignore']); fs.mkdirSync(path.join(root, 'graft/.cache'), { recursive: true }); fs.mkdirSync(path.join(root, 'graphify-out'), { recursive: true }); fs.mkdirSync(path.join(root, '.repository-intelligence'), { recursive: true }); fs.writeFileSync(path.join(root, 'graft/.cache/cards.json'), 'scratch'); fs.writeFileSync(path.join(root, 'graphify-out/graph.json'), 'scratch'); fs.writeFileSync(path.join(root, '.repository-intelligence/state.json'), 'scratch'); execFileSync('git', ['init', '-q'], { cwd: root }); execFileSync('git', ['add', '.gitignore'], { cwd: root }); execFileSync('git', ['-c', 'user.email=installer@test.invalid', '-c', 'user.name=Installer Test', 'commit', '-qm', 'fixture'], { cwd: root }); assert.equal(execFileSync('git', ['status', '--porcelain', '--untracked-files=all'], { cwd: root, encoding: 'utf8' }), '');  const installed = new Set(Object.keys(result.staged)); const links = [...result.staged['docs/toolkit/README.md'].toString().matchAll(/\]\(([^)]+)\)/g)].map((match) => match[1]).filter((href) => href.endsWith('.md')); for (const href of links) assert.ok(installed.has(path.posix.normalize(path.posix.join('docs/toolkit', href))), href); });
test('AC MOD-001 selection displays three descriptions and exact state brackets', async () => { const output = []; const result = await runInstallWizard({ sourceRoot, targetRoot: temp(), ...io(['1', 'n'], output), width: 80 }); assert.equal(result.cancelled, true); const text = output.join('\n'); for (const row of ['1. [ ] core      [NOT INSTALLED] ', '2. [ ] quality   [NOT INSTALLED] ', '3. [ ] extras    [NOT INSTALLED] ']) assert.ok(text.includes(row), row); for (const description of ['Workflow Toolkit, Lean workflow, and shared tooling', 'Deep review and QA skills', 'Optional Ponytail utilities and prompt-review']) assert.ok(text.includes(description), description); });
test('AC MOD-002 dependent selection includes core once and names requester', () => { const result = plan(temp(), ['quality']); assert.deepEqual(result.selectedModules, ['core', 'quality']); assert.deepEqual(result.assessments.find((item) => item.id === 'core').requiredBy, ['quality']); });
test('AC MOD-003 state classification exposes exact five-state vocabulary', () => { const fresh = plan(temp(), ['core']); assert.equal(fresh.assessments[0].status, 'not installed'); const root = temp(); seed(root); assert.equal(plan(root).assessments[0].status, 'up to date'); fs.appendFileSync(path.join(root, '.agents/skills/wtk/SKILL.md'), 'modified'); assert.equal(plan(root).assessments[0].status, 'modified'); });
test('AC MOD-004 deselection removes only module-owned actions and preserves its files/records', () => { const root = temp(); const seeded = seed(root, ['extras']); const before = snapshot(root); const selected = plan(root, ['core']); assert.deepEqual(selected.selectedModules, ['core']); assert.equal(selected.actions.some((action) => action.modules.includes('extras')), false); assert.deepEqual(snapshot(root), before); assert.equal(JSON.parse(fs.readFileSync(path.join(root, '.my-workflow/adoption.json'))).layers.includes('extras'), true); assert.ok(seeded.manifest.files['.agents/skills/ponytail-audit/SKILL.md']); });
test('AC MOD-005 all-current plan has exact message and zero actions', () => { const root = temp(); seed(root); const result = plan(root); assert.equal(result.message, 'Selected modules are up to date. No files will change.'); assert.deepEqual(result.actions, []); });
test('AC STATE-001 rejects malformed version, ownership, hash, and path before planning', () => { const cases = [['version', { schema: 1, workflow_version: '01.0.0', layers: [], files: {}, blocks: {} }, /schema/], ['ownership', { schema: 1, workflow_version: '0.10.0', layers: ['core'], files: { a: { layer: 'core', ownership: 'invalid', source_sha256: '0'.repeat(64), installed_sha256: '0'.repeat(64) } }, blocks: {} }, /ownership/], ['hash', { schema: 1, workflow_version: '0.10.0', layers: ['core'], files: { a: { layer: 'core', ownership: 'managed', source_sha256: 'bad', installed_sha256: '0'.repeat(64) } }, blocks: {} }, /source_sha256/], ['path', { schema: 1, workflow_version: '0.10.0', layers: ['core'], files: { '../outside': { layer: 'core', ownership: 'managed', source_sha256: '0'.repeat(64), installed_sha256: '0'.repeat(64) } }, blocks: {} }, /unsafe/]]; for (const [name, payload, expected] of cases) { const root = temp(); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), JSON.stringify(payload)); assert.throws(() => loadManifest(root), expected, name); assert.deepEqual(fs.readdirSync(root), ['.my-workflow']); } });
test('AC SAFE-001 wizard previews every action before final confirmation', async () => { const output = []; const actions = ['add', 'update', 'claim', 'replace', 'remove', 'preserve', 'no-change', 'conflict'].map((kind) => ({ path: kind, kind, modules: ['core'] })); const fakePlan = { target: '/tmp', actions, unresolved: [] }; const planner = () => ({ plan: { ...fakePlan, assessments: [{ id: 'core', status: 'modified' }], selectedModules: ['core'] }, staged: {} }); const result = await runInstallWizard({ targetRoot: temp(), sourceRoot, planner, ...io(['1', 'y', 'n'], output) }); assert.equal(result.cancelled, true); const text = output.join('\n'); for (const label of ['ADD', 'UPDATE', 'ADOPT', 'REPLACE', 'REMOVE', 'PRESERVE', 'NO CHANGE', 'CONFLICT']) assert.ok(text.indexOf(label) >= 0, label); assert.ok(text.indexOf('CONFLICT') < text.lastIndexOf('Apply this plan?')); });
test('AC SAFE-002 backup deduplicates replace/remove files and precedes mutation', () => { const root = temp(); fs.writeFileSync(path.join(root, 'old'), 'bytes'); fs.writeFileSync(path.join(root, 'removed'), 'gone'); fs.chmodSync(path.join(root, 'old'), 0o640); const prepared = prepareBackup({ targetRoot: root, plan: { packageVersion: '0.10.0', actions: [{ path: 'old', kind: 'replace' }, { path: 'old', kind: 'replace' }, { path: 'removed', kind: 'remove' }] }, staged: {} }); const manifest = JSON.parse(fs.readFileSync(path.join(root, prepared.backup, 'manifest.json'))); assert.deepEqual(manifest.files.map((item) => item.path), ['old', 'removed']); assert.deepEqual(manifest.files.map((item) => item.action), ['replace', 'remove']); assert.equal(manifest.files[0].mode, 0o640); assert.equal(fs.readFileSync(path.join(root, prepared.backup, 'files/old'), 'utf8'), 'bytes'); assert.equal(fs.readFileSync(path.join(root, prepared.backup, 'files/removed'), 'utf8'), 'gone'); assert.equal(fs.readFileSync(path.join(root, 'old'), 'utf8'), 'bytes'); assert.equal(fs.existsSync(path.join(root, '.my-workflow/transaction.json')), true); });
test('AC SAFE-003 backup failure preserves target and adoption state', () => { const root = temp(); fs.writeFileSync(path.join(root, 'old'), 'bytes'); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), 'state'); assert.throws(() => prepareBackup({ targetRoot: root, plan: { actions: [{ path: 'old', kind: 'replace' }] }, staged: {}, failBackup: 'old' }), /old/); assert.equal(fs.readFileSync(path.join(root, 'old'), 'utf8'), 'bytes'); assert.equal(fs.readFileSync(path.join(root, '.my-workflow/adoption.json'), 'utf8'), 'state'); });
test('AC SAFE-004 publication failure returns CLI code 1 and restores complete target state', async () => { const root = temp(); fs.writeFileSync(path.join(root, 'old'), 'bytes'); fs.chmodSync(path.join(root, 'old'), 0o640); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), 'before'); const before = snapshot(root); const output = []; const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', 'y'], output), transaction: (prepared) => applyTransaction(prepared, { failAfter: 'old' }), planner: () => ({ plan: { target: root, selectedModules: ['core'], assessments: [{ id: 'core', status: 'outdated' }], actions: [{ path: 'old', kind: 'replace', modules: ['core'] }], unresolved: [] }, staged: { old: Buffer.from('after'), '.my-workflow/adoption.json': Buffer.from('after-state') } }) }); assert.equal(result.code, 1); assert.equal(fs.readFileSync(path.join(root, 'old'), 'utf8'), 'bytes'); assert.equal(fs.statSync(path.join(root, 'old')).mode & 0o777, 0o640); assert.equal(fs.readFileSync(path.join(root, '.my-workflow/adoption.json'), 'utf8'), 'before'); assert.equal(fs.existsSync(path.join(root, '.my-workflow/transaction.json')), false); assert.ok(fs.existsSync(path.join(root, '.my-workflow/backups'))); assert.match(output.join('\n'), /Installation failed|publication failed/); });
test('AC SAFE-005 conflict choices are required before final confirmation', async () => { const root = temp(); const file = path.join(root, '.agents/skills/wtk/SKILL.md'); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, 'collision'); const output = []; const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', '3'], output) }); assert.equal(result.cancelled, true); assert.match(output.join('\n'), /Back up and replace[\s\S]*Exclude module[\s\S]*Cancel installation/); });
test('AC SAFE-006 cancellation at selection, preview, conflict, and confirmation is residue-free', async () => { const cases = [['selection', [null]], ['preview', ['1', null]], ['confirmation', ['1', 'y', null]]]; for (const [, answers] of cases) { const root = temp(); const before = snapshot(root); const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(answers) }); assert.equal(result.cancelled, true); assert.deepEqual(snapshot(root), before); } const root = temp(); const collision = path.join(root, '.agents/skills/wtk/SKILL.md'); fs.mkdirSync(path.dirname(collision), { recursive: true }); fs.writeFileSync(collision, 'collision'); const before = snapshot(root); const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', '3']) }); assert.equal(result.cancelled, true); assert.deepEqual(snapshot(root), before); assert.equal(fs.existsSync(path.join(root, '.my-workflow/backups')), false); });
test('AC SAFE-007 publishes adoption after every workflow file and reports no-backup text', async () => { const root = temp(); const output = []; const published = []; const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', 'y'], output), transaction: (prepared) => applyTransaction(prepared, { onPublish: (relative) => published.push(relative) }) }); assert.equal(result.code, 0); assert.equal(published.at(-1), '.my-workflow/adoption.json'); assert.ok(published.length > 1); assert.match(output.join('\n'), /Backup: No backup required\./); assert.equal(fs.existsSync(path.join(root, '.my-workflow/adoption.json')), true); });
test('AC KNOW-001 transfer record names source destination reason and status', () => { const item = knowledgeTransfers({ actions: [{ path: 'AGENTS.md', kind: 'replace' }] }, '.my-workflow/backups/x')[0]; assert.deepEqual(Object.keys(item).sort(), ['destination', 'reason', 'source', 'status']); assert.equal(item.status, 'Pending human transfer'); });
test('AC KNOW-002 accepted knowledge replacement never merges into any prohibited destination', async () => { const root = temp(); const first = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', 'y']) }); assert.equal(first.code, 0); const destinations = ['AGENTS.md', 'CLAUDE.md', 'docs/product/AGENT-CONTEXT.md', 'knowledge/wiki/index.md', 'knowledge/wiki/research/index.md', '.claude/agents/planner.md', '.codex/agents/planner.toml', '.cursor/agents/planner.md']; const before = {}; for (const relative of destinations) if (fs.existsSync(path.join(root, relative))) before[relative] = fs.readFileSync(path.join(root, relative)); const agents = path.join(root, 'AGENTS.md'); fs.writeFileSync(agents, fs.readFileSync(agents, 'utf8').replace('<!-- my-workflow:core:end -->', 'consumer-only knowledge\n<!-- my-workflow:core:end -->')); const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', '1', 'y']) }); assert.equal(result.code, 0); for (const [relative, content] of Object.entries(before)) assert.doesNotMatch(fs.readFileSync(path.join(root, relative), 'utf8'), /consumer-only knowledge/, relative); assert.doesNotMatch(fs.readFileSync(path.join(root, '.my-workflow/adoption.json'), 'utf8'), /consumer-only knowledge/); assert.equal(fs.existsSync(path.join(root, '.specs/features/interactive-installer')), false); });
test('AC KNOW-003 successful install persists and displays every transfer field', async () => { const root = temp(); await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', 'y']) }); const agents = path.join(root, 'AGENTS.md'); fs.writeFileSync(agents, fs.readFileSync(agents, 'utf8').replace('<!-- my-workflow:core:end -->', 'consumer-only knowledge\n<!-- my-workflow:core:end -->')); const output = []; const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', '1', 'y'], output) }); assert.equal(result.code, 0); assert.equal(result.knowledge.length, 1); const item = result.knowledge[0]; const checklist = fs.readFileSync(path.join(root, result.result.backup, 'knowledge-transfer.md'), 'utf8'); for (const value of [item.source, item.destination, item.reason, item.status]) { assert.ok(checklist.includes(value), value); assert.ok(output.join('\n').includes(value), value); } assert.ok(output.join('\n').includes('Checklist:')); assert.ok(output.join('\n').includes('knowledge-transfer.md')); });
test('AC KNOW-004 declining knowledge-bearing replacement cancels and preserves original', async () => { const root = temp(); await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', 'y']) }); const file = path.join(root, 'AGENTS.md'); fs.writeFileSync(file, fs.readFileSync(file, 'utf8').replace('<!-- my-workflow:core:end -->', 'consumer-only knowledge\n<!-- my-workflow:core:end -->')); const before = snapshot(root); const output = []; const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['1', 'y', '3'], output) }); assert.equal(result.cancelled, true); assert.deepEqual(snapshot(root), before); assert.match(output.join('\n'), /Cancel installation/); });
test('AC KNOW-005 all fresh knowledge scaffolding is neutral and undated', () => { const root = temp(); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); const generated = Object.entries(result.staged).filter(([relative]) => relative.startsWith('knowledge/wiki/') || relative === 'docs/product/AGENT-CONTEXT.md'); assert.ok(generated.length > 1); for (const [relative, content] of generated) { const text = content.toString(); assert.doesNotMatch(text, /source-pack|source pack|my-workflow|\b20\d\d-\d\d-\d\d\b/i, relative); } });
test('AC CORE-002 packet contract remains complete', async () => { const { stageAgentPackets } = await import('../../scripts/installer/packets.js'); assert.equal(Object.keys(stageAgentPackets(sourceRoot, sourceRoot)).filter((item) => item.includes('/agents/')).length, 18); });
test('AC CORE-003 obsolete adopter and launcher are absent from repository/package', () => { assert.equal(fs.existsSync(path.join(sourceRoot, 'scripts/adopt.py')), false); assert.equal(fs.existsSync(path.join(sourceRoot, 'bin/my-workflow.js')), false); const pkg = JSON.parse(fs.readFileSync(path.join(sourceRoot, 'package.json'))); assert.equal(pkg.files.includes('scripts/adopt.py'), false); });
test('PY-BASELINE-001 every unrelated Python tool retains baseline bytes', () => { const paths = execFileSync('git', ['ls-tree', '-r', '--name-only', '9acea915', '--', '*.py'], { encoding: 'utf8' }).trim().split('\n').filter((relative) => relative && !['scripts/adopt.py', 'scripts/test_adopt.py', 'scripts/install_security_skills.py'].includes(relative)); for (const relative of paths) { const current = path.join(sourceRoot, relative); if (!fs.existsSync(current)) continue; assert.deepEqual(fs.readFileSync(current), execFileSync('git', ['show', `9acea915:${relative}`]), relative); } assert.equal(fs.existsSync(path.join(sourceRoot, 'scripts/install_security_skills.py')), false); });
test('AC SEC-001 catalog, manifest, backup, and target symlink escapes fail with zero outside mutation', () => { const root = temp(); const outside = temp(); fs.writeFileSync(path.join(outside, 'sentinel'), 'outside'); assert.throws(() => restoreInterrupted({ targetRoot: root, journal: { schema: 1, state: 'prepared', backup: '../outside', restore: [], removeOnRestore: [], previousAdoptionState: null } }), /unsafe|inside/); const manifestRoot = temp(); fs.mkdirSync(path.join(manifestRoot, '.my-workflow')); fs.writeFileSync(path.join(manifestRoot, '.my-workflow/adoption.json'), JSON.stringify({ schema: 1, workflow_version: '0.10.0', layers: ['core'], files: { '../outside': {} }, blocks: {} })); assert.throws(() => loadManifest(manifestRoot), /unsafe/); const symlinkRoot = temp(); fs.mkdirSync(path.join(symlinkRoot, '.agents')); fs.symlinkSync(outside, path.join(symlinkRoot, '.agents/skills')); assert.throws(() => plan(symlinkRoot), /symlink/); assert.equal(fs.readFileSync(path.join(outside, 'sentinel'), 'utf8'), 'outside'); assert.deepEqual(fs.readdirSync(root), []); });
test('AC SEC-002 unexpected object names exact path and performs zero publication', () => { const root = temp(); fs.writeFileSync(path.join(root, 'parent'), 'not a directory'); const before = snapshot(root); assert.throws(() => prepareBackup({ targetRoot: root, plan: { actions: [{ path: 'parent/old', kind: 'replace' }] }, staged: {} }), /backup source parent parent must be a directory/); assert.deepEqual(snapshot(root), before); const directoryRoot = temp(); fs.mkdirSync(path.join(directoryRoot, 'old')); const beforeDirectory = snapshot(directoryRoot); assert.throws(() => prepareBackup({ targetRoot: directoryRoot, plan: { actions: [{ path: 'old', kind: 'replace' }] }, staged: {} }), /backup source old must be a file/); assert.deepEqual(snapshot(directoryRoot), beforeDirectory); });
test('AC SEC-003 missing Git fails closed with exact zero-write outcome', async () => { const root = temp(); const before = snapshot(root); const output = []; const result = await runInstallWizard({ sourceRoot, targetRoot: root, requireGit: true, ...io(['1', 'y', 'y'], output), planner: () => { throw new Error('planner must not run'); } }); assert.equal(result.code, 1); assert.match(output.join('\n'), /Git proof failed/); assert.deepEqual(snapshot(root), before); });
test('AC EDGE-001 missing manifest collision has exact conflict state', () => { const root = temp(); const file = path.join(root, '.agents/skills/wtk/SKILL.md'); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, 'collision'); const result = plan(root); assert.equal(result.assessments[0].status, 'conflict'); assert.ok(result.unresolved.includes('.agents/skills/wtk/SKILL.md')); });
test('AC EDGE-002 malformed or unsupported state reports diagnostic and performs no writes', async () => { for (const content of ['{bad', JSON.stringify({ schema: 3, workflow_version: '0.10.0', layers: [], files: {}, blocks: {} })]) { const root = temp(); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), content); const before = snapshot(root); assert.throws(() => plan(root), /invalid adoption manifest|unsupported schema|schema must be version/); assert.deepEqual(snapshot(root), before); } });
test('AC EDGE-003 plan action paths are deduplicated with module ownership', () => { const result = plan(temp(), ['quality']); const paths = result.actions.map((action) => action.path); assert.equal(paths.length, new Set(paths).size); assert.equal(result.actions.every((action) => action.modules.length > 0), true); });
test('AC EDGE-004 process interruption before confirmation leaves target and backup unchanged', async () => { const root = temp(); const before = snapshot(root); await assert.rejects(runInstallWizard({ sourceRoot, targetRoot: root, input: async (prompt) => { if (prompt.includes('Apply this plan')) throw new Error('SIGINT'); return prompt.includes('Modules') ? '1' : 'y'; } }), /SIGINT/); assert.deepEqual(snapshot(root), before); });
test('AC EDGE-005 next run offers recorded restore and blocks mutation when declined', async () => { const root = temp(); fs.writeFileSync(path.join(root, 'old'), 'before'); const prepared = prepareBackup({ targetRoot: root, plan: { actions: [{ path: 'old', kind: 'replace' }] }, staged: {} }); assert.equal(hasInterruptedTransaction(root), true); fs.writeFileSync(path.join(root, 'old'), 'changed'); const before = snapshot(root); const output = []; const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['n'], output) }); assert.equal(result.cancelled, true); assert.deepEqual(snapshot(root), before); assert.match(output.join('\n'), /A previous installation was interrupted\. Restore its recorded backup before continuing\. Restore now\? \(y\/N\):/); assert.equal(fs.existsSync(path.join(root, '.my-workflow/transaction.json')), true); restoreInterrupted({ targetRoot: root, journal: prepared.journal }); });
test('AC EDGE-005 accepted recovery restores before rendering a new plan', async () => { const root = temp(); fs.writeFileSync(path.join(root, 'old'), 'before'); prepareBackup({ targetRoot: root, plan: { actions: [{ path: 'old', kind: 'replace' }] }, staged: {} }); fs.writeFileSync(path.join(root, 'old'), 'changed'); const output = []; const result = await runInstallWizard({ sourceRoot, targetRoot: root, ...io(['y', '1', 'n'], output) }); assert.equal(result.cancelled, true); const text = output.join('\n'); const recovery = text.indexOf('A previous installation was interrupted.'); const welcome = text.indexOf('Workflow Toolkit Installer'); assert.ok(recovery >= 0 && recovery < welcome); assert.equal(fs.readFileSync(path.join(root, 'old'), 'utf8'), 'before'); assert.equal(fs.existsSync(path.join(root, '.my-workflow/transaction.json')), false); });
test('AC SAFE-001/002 ignore updates are visible actions with backup evidence', () => { const root = temp(); fs.writeFileSync(path.join(root, '.gitignore'), 'consumer-ignore\n'); fs.writeFileSync(path.join(root, '.ignore'), 'consumer-search\n'); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); const ignores = result.plan.actions.filter((action) => ['.gitignore', '.ignore'].includes(action.path)); assert.deepEqual(ignores.map((action) => action.kind), ['update', 'update']); assert.ok(result.staged['.gitignore']); assert.ok(result.staged['.ignore']); const rendered = renderPlan(result.plan, 80); assert.ok(rendered.includes('.gitignore')); assert.ok(rendered.includes('.ignore')); const prepared = prepareBackup({ targetRoot: root, plan: result.plan, staged: result.staged }); const paths = JSON.parse(fs.readFileSync(path.join(root, prepared.backup, 'manifest.json'))).files.map((entry) => entry.path); assert.ok(paths.includes('.gitignore')); assert.ok(paths.includes('.ignore')); });
