import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { buildPlan, gitProof, loadManifest, resolveModules, requestedModules, sha256, validateRelative, InstallerError } from '../../scripts/installer/engine.js';

const sourceRoot = path.resolve(import.meta.dirname, '../..');
const target = () => fs.mkdtempSync(path.join(os.tmpdir(), 'installer-engine-'));
const expectError = (fn, text) => assert.throws(fn, (error) => error instanceof InstallerError && (!text || error.message.includes(text)));
const writeResult = (root, result, includeManifest = true) => { for (const [relative, content] of Object.entries(result.staged)) { if (!includeManifest && relative === '.my-workflow/adoption.json') continue; const file = path.join(root, relative); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, content); } for (const [relative, target] of Object.entries(result.links || {})) { const file = path.join(root, relative); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.symlinkSync(target, file); } };
const treeSnapshot = (root) => { const result = {}; const walk = (directory) => { for (const entry of fs.readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) { const file = path.join(directory, entry.name); const relative = path.relative(root, file).split(path.sep).join('/'); if (entry.isSymbolicLink()) result[relative] = `symlink:${fs.readlinkSync(file)}`; else if (entry.isDirectory()) walk(file); else result[relative] = fs.readFileSync(file).toString('base64'); } }; walk(root); return result; };

test('shared workflow references move with provenance-safe retirement', () => {
  const pairs = [['GATES.md', 'validation.md'], ['VERIFICATION-EVIDENCE.md', 'evidence.md'], ['TEST-CONTRACT.md', 'test-contract.md'], ['BRANCHING.md', 'git.md'], ['ARTIFACT-LIFECYCLE.md', 'artifacts.md']];
  for (const state of ['pristine', 'modified', 'unowned']) {
    const consumer = target();
    try {
      const files = {};
      for (const [oldName] of pairs) {
        const relative = `docs/toolkit/guidelines/${oldName}`;
        fs.mkdirSync(path.dirname(path.join(consumer, relative)), { recursive: true });
        fs.writeFileSync(path.join(consumer, relative), state === 'pristine' ? 'original' : 'consumer edit');
        if (state !== 'unowned') files[relative] = { layer: 'core', ownership: 'managed', source_sha256: sha256('original'), installed_sha256: sha256('original') };
      }
      fs.mkdirSync(path.join(consumer, '.my-workflow'));
      fs.writeFileSync(path.join(consumer, '.my-workflow/adoption.json'), JSON.stringify({ schema: 1, workflow_version: '1.0.0', layers: ['core'], files, blocks: {} }));
      const before = treeSnapshot(consumer);
      const result = buildPlan({ sourceRoot, targetRoot: consumer, selectedModules: ['core'] });
      for (const [oldName, newName] of pairs) {
        const oldPath = `docs/toolkit/guidelines/${oldName}`;
        const newPath = `.agents/skills/wtk/references/${newName}`;
        assert.ok(result.staged[newPath], newPath);
        assert.equal(result.staged[oldPath], undefined, oldPath);
        assert.equal(result.plan.actions.find((action) => action.path === oldPath)?.kind, state === 'pristine' ? 'remove' : state === 'modified' ? 'conflict' : undefined);
      }
      assert.deepEqual(treeSnapshot(consumer), before);
    } finally {
      fs.rmSync(consumer, { recursive: true, force: true });
    }
  }
});

test('core installs recovery and construction references for fresh and existing instructions', () => {
  const references = ['context-handoff.md', 'construction-constraints.md'].map((name) => `.agents/skills/wtk/references/${name}`);
  for (const existing of [false, true]) {
    const consumer = target();
    try {
      if (existing) fs.writeFileSync(path.join(consumer, 'AGENTS.md'), '# Consumer rules\n\nKeep consumer context.\n');
      const result = buildPlan({ sourceRoot, targetRoot: consumer, selectedModules: ['core'] });
      const instructions = result.staged['AGENTS.md'].toString();
      if (existing) assert.ok(instructions.startsWith('# Consumer rules\n\nKeep consumer context.\n'));
      for (const relative of references) {
        assert.ok(instructions.includes(relative), relative);
        assert.deepEqual(result.staged[relative], fs.readFileSync(path.join(sourceRoot, relative)));
        assert.equal(result.manifest.files[relative].layer, 'core');
        const content = result.staged[relative].toString();
        for (const [, href] of content.matchAll(/\]\(([^)]+)\)/g)) {
          const destination = path.posix.normalize(path.posix.join(path.posix.dirname(relative), href.split('#')[0]));
          assert.ok(result.manifest.files[destination], `${relative} -> ${destination}`);
        }
      }
      writeResult(consumer, result);
      const repeated = buildPlan({ sourceRoot, targetRoot: consumer, selectedModules: ['core'] });
      assert.equal(repeated.staged['AGENTS.md'], undefined);
      for (const relative of references) assert.equal(repeated.staged[relative], undefined);
    } finally {
      fs.rmSync(consumer, { recursive: true, force: true });
    }
  }
});

test('UT-001 dependency closure includes core once', () => assert.deepEqual(resolveModules(['quality', 'extras']), ['core', 'quality', 'extras']));
test('UT-002 fresh target plans not installed modules', () => { const result = buildPlan({ sourceRoot, targetRoot: target(), selectedModules: ['core'] }).plan; assert.equal(result.assessments[0].status, 'not installed'); });
test('UT-003 manifest loader accepts the empty schema', () => { const root = target(); assert.deepEqual(loadManifest(root).layers, []); });
test('UT-004 pristine records can be read', () => { const root = target(); const first = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); assert.ok(first.manifest.files['.agents/skills/wtk/SKILL.md']); });
test('UT-005 modified owned content is reported as modified and remains unresolved', () => { const root = target(); const first = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); writeResult(root, first, false); fs.mkdirSync(path.join(root, '.my-workflow'), { recursive: true }); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), JSON.stringify(first.manifest)); fs.writeFileSync(path.join(root, '.agents/skills/wtk/SKILL.md'), 'consumer'); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }).plan; assert.ok(result.unresolved.includes('.agents/skills/wtk/SKILL.md')); assert.equal(result.assessments.find((item) => item.id === 'core').status, 'modified'); });
test('SEP-08/SEP-09 legacy generic docs retire only hash-proven managed files', () => { const relative = 'docs/workflow/pack.md'; const pristineBytes = Buffer.from('legacy toolkit doc\n'); const manifestFor = () => ({ schema: 1, workflow_version: '1.0.0', layers: ['core'], files: { [relative]: { layer: 'core', ownership: 'managed', source_sha256: sha256(pristineBytes), installed_sha256: sha256(pristineBytes) } }, blocks: {} }); const pristine = target(); fs.mkdirSync(path.dirname(path.join(pristine, relative)), { recursive: true }); fs.writeFileSync(path.join(pristine, relative), pristineBytes); fs.mkdirSync(path.join(pristine, '.my-workflow')); fs.writeFileSync(path.join(pristine, '.my-workflow/adoption.json'), JSON.stringify(manifestFor())); const retired = buildPlan({ sourceRoot, targetRoot: pristine, selectedModules: ['core'] }).plan; assert.ok(retired.retired.includes(relative)); assert.equal(retired.actions.find((action) => action.path === relative)?.kind, 'remove'); const modified = target(); const modifiedBytes = Buffer.from('consumer edit\n'); fs.mkdirSync(path.dirname(path.join(modified, relative)), { recursive: true }); fs.writeFileSync(path.join(modified, relative), modifiedBytes); fs.mkdirSync(path.join(modified, '.my-workflow')); fs.writeFileSync(path.join(modified, '.my-workflow/adoption.json'), JSON.stringify(manifestFor())); const conflict = buildPlan({ sourceRoot, targetRoot: modified, selectedModules: ['core'] }).plan; assert.ok(conflict.unresolved.includes(relative)); assert.equal(conflict.actions.find((action) => action.path === relative)?.kind, 'conflict'); assert.deepEqual(fs.readFileSync(path.join(modified, relative)), modifiedBytes); const unknown = target(); fs.mkdirSync(path.dirname(path.join(unknown, relative)), { recursive: true }); fs.writeFileSync(path.join(unknown, relative), modifiedBytes); const preserved = buildPlan({ sourceRoot, targetRoot: unknown, selectedModules: ['core'] }).plan; assert.equal(preserved.actions.some((action) => action.path === relative), false); assert.deepEqual(fs.readFileSync(path.join(unknown, relative)), modifiedBytes); });
test('UT-006 EDGE-001 unowned collision is a conflict state', () => { const root = target(); const file = path.join(root, '.agents/skills/wtk/SKILL.md'); fs.mkdirSync(path.dirname(file), { recursive: true }); fs.writeFileSync(file, 'collision'); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }).plan; assert.ok(result.unresolved.includes('.agents/skills/wtk/SKILL.md')); assert.equal(result.assessments.find((item) => item.id === 'core').status, 'conflict'); });
test('UT-007 selected modules are dependency closed', () => assert.deepEqual(buildPlan({ sourceRoot, targetRoot: target(), selectedModules: ['extras'] }).plan.selectedModules, ['core', 'extras']));
test('UT-008 actions carry owning module', () => { const result = buildPlan({ sourceRoot, targetRoot: target(), selectedModules: ['quality'] }).plan; assert.ok(result.actions.some((action) => action.modules.includes('quality'))); });
test('UT-011 fresh scaffolding uses package bytes', () => { const root = target(); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); assert.equal(result.staged['knowledge/wiki/index.md'].toString(), fs.readFileSync(path.join(sourceRoot, 'templates/adoption/knowledge/wiki/index.md'), 'utf8')); });
test('IT-012 malformed manifest paths fail closed before plan', () => { const root = target(); fs.mkdirSync(path.join(root, '.my-workflow'), { recursive: true }); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), JSON.stringify({ schema: 1, workflow_version: '0.10.0', layers: ['core'], files: { '../outside': {} }, blocks: {} })); expectError(() => loadManifest(root), 'unsafe'); });
test('UT-012 absolute paths fail validation', () => expectError(() => validateRelative('/outside'), 'unsafe'));
test('UT-012 unsupported module fails validation', () => expectError(() => resolveModules(['unknown']), 'unknown'));
test('UT-013 no-op message is exact with zero plan actions', () => { const root = target(); const first = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); writeResult(root, first, false); fs.mkdirSync(path.join(root, '.my-workflow'), { recursive: true }); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), first.staged['.my-workflow/adoption.json']); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }).plan; assert.equal(result.message, 'Selected modules are up to date. No files will change.'); assert.deepEqual(result.actions, []); });
test('UT-014 comma-separated modules are normalized', () => assert.deepEqual(requestedModules('quality, quality'), ['quality']));
test('SEC-001 traversal is rejected before access', () => expectError(() => validateRelative('../escape'), 'unsafe'));
test('SEC-004 hashes are deterministic and literal', () => assert.equal(sha256(Buffer.from('literal')), '829f8d848b44fa3098194754af5b60e2fb1517b0195956841beb6cac9bc68067'));
test('SEC-006 unsupported schema fails closed', () => expectError(() => loadManifest((() => { const root = target(); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), '{"schema":3}'); return root; })()), 'unsupported schema'));
test('SEC-003 Git proof uses literal argv, target cwd, and shell false', () => { const root = target(); const calls = []; const runner = (command, args, options) => { calls.push({ command, args, options }); if (args[0] === 'rev-parse' && args[1] === '--is-inside-work-tree') return 'true'; if (args[1] === '--show-toplevel') return root; if (args[1] === '--verify') return 'HEAD'; return ''; }; assert.equal(gitProof(root, runner), true); assert.deepEqual(calls.map((call) => call.command), ['git', 'git', 'git', 'git']); assert.equal(calls.every((call) => call.options.cwd === root && call.options.shell === false), true); });
test('SEC-003 missing Git proof fails closed', () => expectError(() => gitProof(target(), () => { throw new Error('ENOENT'); }), 'Git proof failed'));
test('SEC-003 dirty Git proof fails before publication', () => expectError(() => gitProof(target(), (_command, args) => args[1] === '--is-inside-work-tree' ? 'true' : args[1] === '--show-toplevel' ? '/tmp' : 'dirty'), 'target must be the root'));

test('UT-007 deselection preserves remaining actions and exact excluded records', () => { const root = target(); const extras = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['extras'] }); const before = new Map(Object.entries(extras.manifest.files)); const core = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }).plan; assert.ok(core.actions.some((action) => action.modules.includes('core'))); assert.equal(core.actions.some((action) => action.modules.includes('extras')), false); assert.deepEqual(new Map(Object.entries(extras.manifest.files)), before); });
test('UT-008 core-owned skills stay isolated from extras while dependencies remain explicit', () => { const result = buildPlan({ sourceRoot, targetRoot: target(), selectedModules: ['extras'] }).plan; const coreSkill = result.actions.find((action) => action.path === '.agents/skills/ponytail/SKILL.md'); assert.deepEqual(coreSkill.modules, ['core']); assert.equal(result.actions.filter((action) => action.path === coreSkill.path).length, 1); assert.deepEqual(result.assessments.find((item) => item.id === 'core').requiredBy, ['extras']); assert.deepEqual(result.assessments.find((item) => item.id === 'extras').requiredBy, []); });
test('UT-011 every generated wiki scaffold is package-neutral', () => { const result = buildPlan({ sourceRoot, targetRoot: target(), selectedModules: ['core'] }); const files = Object.entries(result.staged).filter(([relative]) => relative.startsWith('knowledge/wiki/') || relative === 'docs/product/AGENT-CONTEXT.md'); assert.ok(files.length > 1); for (const [relative, content] of files) assert.doesNotMatch(content.toString(), /source-pack|my-workflow|\b20\d\d-\d\d-\d\d\b/i, relative); });
test('UT-012 malformed version and invalid hash are rejected independently', () => { for (const record of [{ workflow_version: '1.0', file: { layer: 'core', ownership: 'managed', source_sha256: '0'.repeat(64), installed_sha256: '0'.repeat(64) } }, { workflow_version: '0.10.0', file: { layer: 'core', ownership: 'managed', source_sha256: 'not-a-hash', installed_sha256: '0'.repeat(64) } }]) { const root = target(); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), JSON.stringify({ schema: 1, workflow_version: record.workflow_version, layers: ['core'], files: { 'a.txt': record.file }, blocks: {} })); assert.throws(() => loadManifest(root), /schema must be version 1|source_sha256/); assert.deepEqual(fs.readdirSync(root), ['.my-workflow']); } });
test('SEC-001 manifest traversal and catalog symlink reject before outside access', () => { const root = target(); const outside = target(); fs.writeFileSync(path.join(outside, 'sentinel'), 'outside'); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), JSON.stringify({ schema: 1, workflow_version: '0.10.0', layers: ['core'], files: { '../../outside/sentinel': { layer: 'core', ownership: 'managed', source_sha256: '0'.repeat(64), installed_sha256: '0'.repeat(64) } }, blocks: {} })); expectError(() => loadManifest(root), 'unsafe'); const source = target(); fs.symlinkSync(path.join(outside, 'sentinel'), path.join(source, 'docs')); assert.throws(() => buildPlan({ sourceRoot: source, targetRoot: target(), selectedModules: ['core'] }), /symlink|missing/); assert.equal(fs.readFileSync(path.join(outside, 'sentinel'), 'utf8'), 'outside'); });
test('SEC-004 Git proof treats real shell metacharacters as literal target data', () => { const marker = `installer-marker-${Date.now()}`; const root = fs.mkdtempSync(path.join(os.tmpdir(), `installer;$(touch ${marker})-`)); const calls = []; const runner = (command, args, options) => { calls.push({ command, args, options }); if (args[1] === '--is-inside-work-tree') return 'true'; if (args[1] === '--show-toplevel') return root; if (args[1] === '--verify') return 'HEAD'; return ''; }; assert.equal(gitProof(root, runner), true); assert.deepEqual(calls.map(({ command, args }) => [command, args]), [['git', ['rev-parse', '--is-inside-work-tree']], ['git', ['rev-parse', '--show-toplevel']], ['git', ['rev-parse', '--verify', 'HEAD']], ['git', ['status', '--porcelain', '--untracked-files=all']]]); assert.ok(calls.every(({ options }) => options.cwd === root && options.shell === false)); assert.equal(fs.existsSync(path.join(os.tmpdir(), marker)), false); });
test('SEC-006 invalid ownership and hash never reaches module assessment', () => { const root = target(); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), JSON.stringify({ schema: 1, workflow_version: '0.10.0', layers: ['core'], files: { 'a.txt': { layer: 'core', ownership: 'consumerish', source_sha256: '0'.repeat(64), installed_sha256: '0'.repeat(64) } }, blocks: {} })); assert.throws(() => buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }), /ownership/); assert.deepEqual(fs.readdirSync(root), ['.my-workflow']); });
test('SEC-001 every target pre-composition root rejects symlinks before outside reads', () => { const outside = target(); fs.writeFileSync(path.join(outside, 'sentinel'), 'outside'); for (const relative of ['AGENTS.md', 'CLAUDE.md', '.gitignore', '.ignore']) { const root = target(); fs.symlinkSync(path.join(outside, 'sentinel'), path.join(root, relative)); assert.throws(() => buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }), /symlink/); assert.equal(fs.readFileSync(path.join(outside, 'sentinel'), 'utf8'), 'outside'); } const root = target(); fs.symlinkSync(outside, path.join(root, '.my-workflow')); assert.throws(() => buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }), /manifest|symlink/); assert.equal(fs.readFileSync(path.join(outside, 'sentinel'), 'utf8'), 'outside'); });
test('SEC-002 Claude skill alias parent symlink fails before target publication', () => { const root = target(); const outside = target(); fs.writeFileSync(path.join(outside, 'sentinel'), 'outside'); fs.symlinkSync(outside, path.join(root, '.claude')); const before = fs.readFileSync(path.join(outside, 'sentinel')); expectError(() => buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }), 'Claude skill link'); assert.deepEqual(fs.readFileSync(path.join(outside, 'sentinel')), before); });
test('SEC-002 Claude skill alias destination collisions fail before mutation', () => { for (const [kind, seed] of [['regular file', (alias) => fs.writeFileSync(alias, 'consumer')], ['wrong-target symlink', (alias) => fs.symlinkSync('../../.agents/skills/other', alias)]]) { const root = target(); const relative = '.claude/skills/wtk-plan'; const alias = path.join(root, relative); fs.mkdirSync(path.dirname(alias), { recursive: true }); seed(alias); const before = treeSnapshot(root); assert.throws(() => buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }), (error) => error instanceof InstallerError && error.message.includes(relative), kind); assert.deepEqual(treeSnapshot(root), before, kind); } });
test('STATE-001 rejects future provenance, consumer hashes, and uninstalled blocks before planning', () => { const cases = [{ version: '1.0.6', files: {}, blocks: {} }, { version: '0.11.0', files: { 'a.txt': { layer: 'core', ownership: 'consumer', source_sha256: '0'.repeat(64), installed_sha256: '0'.repeat(64) } }, blocks: {} }, { version: '0.11.0', files: {}, blocks: { 'AGENTS.md:quality': { sha256: '0'.repeat(64) } } }]; for (const value of cases) { const root = target(); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), JSON.stringify({ schema: 1, workflow_version: value.version, layers: ['core'], files: value.files, blocks: value.blocks })); assert.throws(() => loadManifest(root), /newer|installed_sha256.*null|block record is invalid/); assert.deepEqual(fs.readdirSync(root), ['.my-workflow']); } });
test('STATE-001 semver boundaries compare major, minor, and patch lexicographically', () => { for (const [version, accepted] of [['0.9.2', true], ['0.10.1', true], ['0.11.0', true], ['1.0.1', true], ['1.0.2', true], ['1.0.3', true], ['1.0.4', true], ['1.0.5', true], ['1.0.6', false], ['2.0.0', false]]) { const root = target(); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), JSON.stringify({ schema: 1, workflow_version: version, layers: [], files: {}, blocks: {} })); if (accepted) assert.equal(loadManifest(root).workflow_version, version); else assert.throws(() => loadManifest(root), /newer/); } });
test('SEC-001 invalid UTF-8 instructions fail before composition or target mutation', () => { const root = target(); const bytes = Buffer.from([0x23, 0x20, 0xff, 0x0a]); fs.writeFileSync(path.join(root, 'AGENTS.md'), bytes); assert.throws(() => buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }), /AGENTS\.md instruction is not valid UTF-8/); assert.deepEqual(fs.readFileSync(path.join(root, 'AGENTS.md')), bytes); assert.deepEqual(fs.readdirSync(root), ['AGENTS.md']); });
test('MOD-004 deselection leaves installed module files and records untouched', () => { const root = target(); const seeded = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['extras'] }); writeResult(root, seeded); const before = fs.readFileSync(path.join(root, '.my-workflow/adoption.json')); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }).plan; assert.deepEqual(result.selectedModules, ['core']); assert.equal(result.actions.some((action) => action.modules.includes('extras')), false); assert.deepEqual(fs.readFileSync(path.join(root, '.my-workflow/adoption.json')), before); });
test('MOD-003 pristine seeded content is up to date', () => { const root = target(); const seeded = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); writeResult(root, seeded); const result = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }).plan; assert.equal(result.assessments[0].status, 'up to date'); });
test('UT-004 packaged source drift is outdated while target stays pristine', () => { const root = target(); const variant = target(); fs.cpSync(sourceRoot, variant, { recursive: true, filter: (item) => !item.includes(`${path.sep}node_modules${path.sep}`) && !item.includes(`${path.sep}.git${path.sep}`) }); const seeded = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['core'] }); writeResult(root, seeded); fs.appendFileSync(path.join(variant, 'docs/toolkit/README.md'), '\nnew package source\n'); const result = buildPlan({ sourceRoot: variant, targetRoot: root, selectedModules: ['core'] }).plan; assert.equal(result.assessments[0].status, 'outdated'); fs.rmSync(variant, { recursive: true, force: true }); });
test('IT-012 normalized plan output is deterministic across repeated reads', () => { const root = target(); const first = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['quality'] }).plan; const second = buildPlan({ sourceRoot, targetRoot: root, selectedModules: ['quality'] }).plan; assert.deepEqual(first.actions, second.actions); assert.deepEqual(first.unresolved, second.unresolved); });
test('STATE-001 invalid ownership and hash fail before target mutation', () => { const root = target(); fs.mkdirSync(path.join(root, '.my-workflow')); fs.writeFileSync(path.join(root, '.my-workflow/adoption.json'), JSON.stringify({ schema: 1, workflow_version: '0.10.0', layers: ['core'], files: { 'a.txt': { layer: 'core', ownership: 'other', source_sha256: 'bad', installed_sha256: 'bad' } }, blocks: {} })); assert.throws(() => loadManifest(root), /invalid/); assert.deepEqual(fs.readdirSync(root), ['.my-workflow']); });
test('SEC-001 catalog symlink fails closed before source omission', () => { const variant = target(); fs.cpSync(sourceRoot, variant, { recursive: true, filter: (item) => !item.includes(`${path.sep}node_modules${path.sep}`) && !item.includes(`${path.sep}.git${path.sep}`) }); const outside = target(); const sourceFile = path.join(variant, 'docs/toolkit/guidelines/DX.md'); fs.unlinkSync(sourceFile); fs.symlinkSync(path.join(outside, 'sentinel'), sourceFile); fs.writeFileSync(path.join(outside, 'sentinel'), 'outside'); assert.throws(() => buildPlan({ sourceRoot: variant, targetRoot: target(), selectedModules: ['core'] }), /symlink/); assert.equal(fs.readFileSync(path.join(outside, 'sentinel'), 'utf8'), 'outside'); fs.rmSync(variant, { recursive: true, force: true }); });
